### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by AFAgarap** [iamcjdizon/practice-programming-problems#1]
The files you have uploaded are text files. Kindly upload the Java file (<filename>.java).

**Comment by AFAgarap** [comment]
Since you have uploaded your programming solutions (the ones with file extenstions), you may remove those without file extensions now. It would be `git rm <file-to-remove>`. Then, commit the removal of the files, and push it to your repository. Happy coding! :)

**Comment by iamcjdizon** [comment]
Alright.

**Comment by AFAgarap** [comment]
Your repository is well-organized. :+1:

**Comment by iamcjdizon** [comment]
I'm a bit OC ee. hahaaha.
