### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AFAgarap** [iamcjdizon/practice-programming-problems#3]
Please write a text file where you are explaining how you approached each programming problems last July 27, 2015.

**Comment by iamcjdizon** [comment]
Oh right. Yes. will do.

**Comment by AFAgarap** [comment]
So far, you're doing a great job, @iamcjdizon Kudos! :+1:

**Comment by iamcjdizon** [comment]
Thank you! I wish i could maintain it! :))

**Comment by AFAgarap** [comment]
@iamcjdizon You should. :+1: Hoping to see the documentation soon

**Comment by iamcjdizon** [comment]
Uploaded. :)

**Comment by AFAgarap** [comment]
Nice!
